name: Konbini Guard

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 */3 * *"

jobs:
    konbini-guard:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Install Bun
              uses: oven-sh/setup-bun@v2.0.2
              with:
                  bun-version: "latest"

            - name: Setup Git
              uses: qoomon/actions--setup-git@v1
              with:
                  user: bot

            - name: Install ClamAV
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends clamav clamav-base libclamav12

            # MAYBE this fixes the thing
            - name: Manual freshclam
              run: |
                  mkdir -p /tmp/clamav
                  sudo chown $USER:$USER /tmp/clamav
                  wget -q --tries=3 https://database.clamav.net/main.cvd -O /tmp/clamav/main.cvd || true
                  wget -q --tries=3 https://database.clamav.net/daily.cvd -O /tmp/clamav/daily.cvd || true
                  wget -q --tries=3 https://database.clamav.net/bytecode.cvd -O /tmp/clamav/bytecode.cvd || true

            - name: Run guard
              run: |
                  bun install
                  cd ./packages/client/guard
                  bun guard.ts
              env:
                  BEARER: ${{ secrets.BEARER }}
                  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_URL }}
                  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_TOKEN }}

            - name: Push changes
              run: |
                  git add -A
                  (git commit -m "Konbini Guard automated run") || echo "No changes made."
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
