name: Konbini Guard

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 */3 * *"

permissions:
    contents: write

jobs:
    konbini-guard:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Install Bun
              uses: oven-sh/setup-bun@v2.0.2
              with:
                  bun-version: "latest"

            - name: Install ClamAV
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends clamav clamav-base libclamav12

            # MAYBE this fixes the thing
            - name: Manual freshclam
              run: |
                  mkdir -p /tmp/clamav
                  sudo chown $USER:$USER /tmp/clamav
                  wget -q --tries=3 https://database.clamav.net/main.cvd -O /tmp/clamav/main.cvd || true
                  wget -q --tries=3 https://database.clamav.net/daily.cvd -O /tmp/clamav/daily.cvd || true
                  wget -q --tries=3 https://database.clamav.net/bytecode.cvd -O /tmp/clamav/bytecode.cvd || true

            - name: Run guard
              run: |
                  bun install
                  cd ./packages/client/guard
                  bun guard.ts
                  bun install -g vercel
              env:
                  BEARER: ${{ secrets.BEARER }}
                  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_URL }}
                  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_TOKEN }}

            - name: Push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add -A
                  (git commit -m "Konbini Guard automated run") || echo "No changes made."
                  git push
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Deploy changes
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ID_ORG: ${{ secrets.VERCEL_ID_ORG }}
                  VERCEL_ID_PROJECT: ${{ secrets.VERCEL_ID_PROJECT }}
              run: |
                  mkdir -p ./packages/data/.vercel
                  echo "{\"projectId\":\"$VERCEL_ID_PROJECT\",\"orgId\":\"$VERCEL_ID_ORG\",\"projectName\":\"konbini-data\"}" > ./packages/data/.vercel/project.json
                  vercel --prod --token $VERCEL_TOKEN --confirm
